services:
  api:
    image: gastroapi:latest
    build:      
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=myapp;Username=postgres;Password=postgres"
    ports:
      - "8001:80"  
    depends_on:
      - "db"
    networks:
      - dev
      # - elastic

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dev

  # es01:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
  #   environment:
  #     - node.name=es01
  #     - cluster.name=es-docker-cluster
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - xpack.security.enabled=false
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data01:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - elastic

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.7.1
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://localhost:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - es01
  #   networks:
  #     - elastic

networks:
  dev:
    driver: bridge
  # elastic:
  #   driver: bridge

volumes:
    db_data:
      driver: local
  # data01:
  #   driver: local